springdoc:
  swagger-ui:
    use-root-path: true

spring:
  datasource:
    url: jdbc:h2:mem:exploringDesignPatterns
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true